on: [push, pull_request]

jobs:
  op_job:
    runs-on: ubuntu-latest
    name: Open Bullet
    steps:
      # To use this repository's private action,
      # you must check out the repository
      - name: Checkout
        uses: actions/checkout@v2
      - name: Hello world action step
        uses: ./ # Uses an action in the root directory
        
